name: Debug Repository Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show repository structure
        run: |
          echo "=== Root Directory Contents ==="
          dir
          echo ""
          echo "=== Looking for package.json files ==="
          dir /s package.json
          echo ""
          echo "=== Check if Backend folder exists ==="
          if exist Backend (echo Backend folder exists) else (echo Backend folder NOT found)
          echo ""
          echo "=== List all folders ==="
          dir /ad
