name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'Backend/package-lock.json'
        
    - name: Debug Backend structure
      run: |
        echo "=== Backend directory contents ==="
        ls -la Backend/
        echo "=== Checking for lock file ==="
        if [ -f "Backend/package-lock.json" ]; then
          echo "✅ package-lock.json found"
        else
          echo "❌ package-lock.json not found"
        fi
        
    - name: Install Backend dependencies
      run: |
        cd Backend
        # Generate lock file if it doesn't exist
        if [ ! -f "package-lock.json" ]; then
          echo "Generating package-lock.json..."
          npm install --package-lock-only
        fi
        npm ci
        
    - name: Build Backend
      run: |
        cd Backend
        npm run build --if-present
        
    - name: Test Backend
      run: |
        cd Backend
        # Skip tests if no real tests are configured
        if npm run test --dry-run 2>&1 | grep -q "Error: no test specified"; then
          echo "No tests specified, skipping test step"
        else
          npm run test
        fi
        
    - name: Prepare deployment package
      run: |
        echo "=== Preparing Backend deployment package ==="
        mkdir -p deployment-package
        
        # Copy Backend files to deployment package
        cp -r Backend/* deployment-package/
        
        # Remove development files to reduce size
        cd deployment-package
        rm -rf node_modules/ || echo "No node_modules to remove"
        rm -rf coverage/ || echo "No coverage to remove"
        rm -rf tests/ || echo "No tests to remove"
        rm -rf .git/ || echo "No .git to remove"
        
        echo "=== Deployment package contents ==="
        ls -la
        
    - name: Upload Backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-app
        path: deployment-package
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-app
        path: ./backend-app
        
    - name: Verify deployment package
      run: |
        echo "=== Downloaded artifact contents ==="
        ls -la backend-app/
        echo "=== Checking package.json ==="
        if [ -f "backend-app/package.json" ]; then
          echo "✅ package.json found"
          echo "Package name and scripts:"
          cat backend-app/package.json | grep -E '"name"|"main"|"scripts"' -A 10 || echo "Could not parse package.json"
        else
          echo "❌ ERROR: package.json not found!"
          exit 1
        fi
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49D233250A184B2A8D5512AF424C292C }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9698AE7E77CD405E9B9205CFAC7C7CEB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DA6E6E939E54841AF3E1A1E9908AD29 }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TexasCollegeBackend'
        slot-name: 'Production'
        package: ./backend-app
