name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Change to Backend directory and install
      run: |
        echo "=== Current location ==="
        pwd
        echo "=== Root contents ==="
        ls -la
        echo "=== Moving to Backend folder ==="
        cd Backend
        echo "=== Backend contents ==="
        ls -la
        echo "=== Installing dependencies ==="
        npm install

    - name: Build Backend
      run: |
        cd Backend
        npm run build --if-present

    - name: Test Backend
      run: |
        cd Backend
        npm run test --if-present

    - name: Upload Backend files
      uses: actions/upload-artifact@v4
      with:
        name: backend-app
        path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_49D233250A184B2A8D5512AF424C292C }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9698AE7E77CD405E9B9205CFAC7C7CEB }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DA6E6E939E54841AF3E1A1E9908AD29 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'TexasCollegeBackend'
        slot-name: 'Production'
        package: .
